version: '3.8'
services:
  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment: 
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: organica
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    volumes:
      - ./init:/docker-entrypoint-initdb.d

  backend:
    build:
      context: ./Server
      dockerfile: Dockerfile
    restart: on-failure
    environment:
      # AÃ±adimos createDatabaseIfNotExist y serverTimezone para evitar errores comunes de JDBC
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/organica?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - RAZORPAY_KEY_ID=tu_llave_aqui
      - RAZORPAY_KEY_SECRET=tu_secreto_aqui
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.MySQL8Dialect
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - "9090:9090"
    depends_on:
      - mysql

  frontend:
    build:
      context: ./Client
      dockerfile: Dockerfile
    ports:
      - "3000:80"